# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: csv_madness 0.0.12 ruby lib

Gem::Specification.new do |s|
  s.name = "csv_madness".freeze
  s.version = "0.0.12".freeze

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Bryce Anderson".freeze]
  s.date = "1980-01-02"
  s.description = "CSV Madness removes what little pain is left from Ruby's CSV class.  Load a CSV file, and get back an array of objects with customizable getter/setter methods.".freeze
  s.email = "keeputahweird@gmail.com".freeze
  s.extra_rdoc_files = [
    "CHANGELOG.markdown",
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "./lib/csv_madness.rb",
    "./lib/csv_madness/builder.rb",
    "./lib/csv_madness/data_accessor_module.rb",
    "./lib/csv_madness/exceptions.rb",
    "./lib/csv_madness/gem_api.rb",
    "./lib/csv_madness/record.rb",
    "./lib/csv_madness/sheet.rb",
    "./lib/csv_madness/sheet_methods/base.rb",
    "./lib/csv_madness/sheet_methods/class_methods.rb",
    "./lib/csv_madness/sheet_methods/column_methods.rb",
    "./lib/csv_madness/sheet_methods/file_methods.rb",
    "./lib/csv_madness/sheet_methods/indexing.rb",
    "./lib/csv_madness/sheet_methods/record_methods.rb",
    "./test/csv/forbidden_column.csv",
    "./test/csv/simple.csv",
    "./test/csv/splitter.csv",
    "./test/csv/test_column_types.csv",
    "./test/csv/with_nils.csv",
    "./test/helper.rb",
    "./test/test_builder.rb",
    "./test/test_csv_madness.rb",
    "./test/test_merging_columns.rb",
    "./test/test_reloading_spreadsheet.rb",
    "./test/test_sheet.rb",
    "CHANGELOG.markdown",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION"
  ]
  s.homepage = "http://github.com/darthschmoo/csv_madness".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "4.0.14".freeze
  s.summary = "CSV Madness turns your CSV rows into happycrazy objects.".freeze

  s.specification_version = 4

  s.add_runtime_dependency(%q<csv>.freeze, [">= 0".freeze])
  s.add_runtime_dependency(%q<fun_with_gems>.freeze, ["~> 0.0".freeze, ">= 0.0.7".freeze])
  s.add_development_dependency(%q<fun_with_testing>.freeze, [">= 0".freeze])
end

