# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: csv_madness 0.0.6 ruby lib

Gem::Specification.new do |s|
  s.name = "csv_madness"
  s.version = "0.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Bryce Anderson"]
  s.date = "2014-06-25"
  s.description = "CSV Madness removes what little pain is left from Ruby's CSV class.  Load a CSV file, and get back an array of objects with customizable getter/setter methods."
  s.email = "keeputahweird@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "./lib/csv_madness.rb",
    "./lib/csv_madness/builder.rb",
    "./lib/csv_madness/data_accessor_module.rb",
    "./lib/csv_madness/gem_api.rb",
    "./lib/csv_madness/record.rb",
    "./lib/csv_madness/sheet.rb",
    "./test/csv/forbidden_column.csv",
    "./test/csv/simple.csv",
    "./test/csv/splitter.csv",
    "./test/csv/test_column_types.csv",
    "./test/csv/with_nils.csv",
    "./test/helper.rb",
    "./test/test_builder.rb",
    "./test/test_csv_madness.rb",
    "./test/test_merging_columns.rb",
    "./test/test_reloading_spreadsheet.rb",
    "./test/test_sheet.rb",
    "CHANGELOG.markdown",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION"
  ]
  s.homepage = "http://github.com/darthschmoo/csv_madness"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "CSV Madness turns your CSV rows into happycrazy objects."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<fun_with_gems>, [">= 0.0.2", "~> 0.0"])
      s.add_development_dependency(%q<fun_with_testing>, [">= 0"])
    else
      s.add_dependency(%q<fun_with_gems>, [">= 0.0.2", "~> 0.0"])
      s.add_dependency(%q<fun_with_testing>, [">= 0"])
    end
  else
    s.add_dependency(%q<fun_with_gems>, [">= 0.0.2", "~> 0.0"])
    s.add_dependency(%q<fun_with_testing>, [">= 0"])
  end
end

